/**
 * Form wizard mocks for the cliente preview harness (Playwright evidence, F4-3).
 * Dev-only; never imported by production pages. Covers all 6 field types,
 * prefill ("Ya lo tenemos"), Mi Historia (dictation) and the submitted state.
 */

import type { WizardForm, WizardLabels } from "@/frontend/features/form-wizard";

export const wizardLabelsMock: WizardLabels = {
  stepCounter: "Paso {n} de {total}",
  back: "Atrás",
  saving: "Guardando…",
  saved: "Guardado",
  queued: "Guardado en este dispositivo · pendiente de envío",
  saveError: "Reintentando…",
  saveBlocked: "No pudimos guardar. Recarga la página para continuar.",
  saveBlockedSubmitted: "Este formulario ya fue enviado. Recarga para ver la versión final.",
  offlineBanner: "Sin conexión. Tus respuestas se guardan en este dispositivo y se enviarán al reconectar.",
  prefillChip: "Ya lo tenemos",
  prefillFromDocument: "lo tomamos de tu acta de nacimiento",
  prefillFromProfile: "lo tomamos de tu perfil",
  prefillFromGeneration: "lo tomamos de tu solicitud",
  prefillEdited: "Lo cambiaste tú",
  prefillAiBadge: "IA",
  selectPlaceholder: "Elige una opción",
  textareaPlaceholder: "Escribe aquí, o toca el micrófono para hablar…",
  checkboxYes: "Sí",
  errRequired: "Esto nos hace falta para continuar.",
  errRegex: "Revisa el formato, por favor.",
  errMin: "Es un poco corto. ¿Puedes ampliar?",
  errMax: "Es demasiado largo. Acórtalo un poco.",
  next: "Siguiente",
  finish: "Terminar",
  submitting: "Enviando…",
  submitErrorTitle: "No pudimos enviarlo",
  submitErrorBody: "Vuelve a intentarlo en un momento.",
  privacyNote: "Tu información está protegida y es confidencial",
  dictateIdle: "Tocar para hablar",
  dictateActive: "Escuchando… toca para parar",
  dictateUnsupported: "El dictado no está disponible aquí. Puedes escribir.",
  submittedPill: "Enviado",
  submittedTitle: "¡Listo! Lo recibimos",
  submittedBody: "Tu equipo lo está revisando.",
  approvedPill: "Aprobado",
  reviewClientBanner: "Este formulario lo responde el cliente. ¿Falta algo? Pídeselo por mensaje.",
  reviewClientEditBanner: "Estás llenando este formulario en nombre del cliente. Los cambios se guardan solos.",
  rejectionTitle: "Necesita una corrección",
  rejectionDueLabel: "Fecha límite: {date}",
};

/** Generic PDF form — "Datos del menor", 3 steps, all 6 field types + prefill. */
export const wizardFormMock: WizardForm = {
  responseId: "resp-1",
  formDefinitionId: "form-1",
  labelI18n: { es: "Datos del menor", en: "Minor's details" },
  kind: "pdf_automation",
  sourceLanguage: "en",
  isPerParty: true,
  versionId: "v1",
  status: "draft",
  submittedAt: null,
  filledPdfPath: null,
  filledBy: "client",
  groups: [
    {
      id: "g1",
      titleI18n: { es: "Identidad del menor", en: "Minor's identity" },
      position: 0,
      questions: [
        {
          id: "q1",
          groupId: "g1",
          questionI18n: { es: "Nombre completo del menor", en: "Minor's full name" },
          helpI18n: {
            es: "Tal como aparece en su acta de nacimiento.",
            en: "As it appears on the birth certificate.",
          },
          fieldType: "text",
          options: null,
          isRequired: true,
          position: 0,
          source: "document_extraction",
          validation: null,
          prefillValue: "Mateo Restrepo",
          isPrefilled: true,
          currentAnswer: null,
        },
        {
          id: "q2",
          groupId: "g1",
          questionI18n: { es: "Fecha de nacimiento", en: "Date of birth" },
          helpI18n: { es: "Día, mes y año.", en: "Day, month and year." },
          fieldType: "date",
          options: null,
          isRequired: true,
          position: 1,
          source: "client_answer",
          validation: null,
          prefillValue: null,
          isPrefilled: false,
          currentAnswer: null,
        },
        {
          id: "q3",
          groupId: "g1",
          questionI18n: { es: "¿Está inscrito en la escuela?", en: "Is the minor enrolled in school?" },
          helpI18n: null,
          fieldType: "checkbox",
          options: null,
          isRequired: false,
          position: 2,
          source: "client_answer",
          validation: null,
          prefillValue: null,
          isPrefilled: false,
          currentAnswer: null,
        },
      ],
    },
    {
      id: "g2",
      titleI18n: { es: "Situación actual", en: "Current situation" },
      position: 1,
      questions: [
        {
          id: "q4",
          groupId: "g2",
          questionI18n: { es: "¿Quién tiene la custodia hoy?", en: "Who has custody today?" },
          helpI18n: {
            es: "Elige la opción que mejor describe la situación.",
            en: "Pick the option that best fits.",
          },
          fieldType: "select",
          options: [
            { value: "mother", labelI18n: { es: "La madre", en: "The mother" } },
            { value: "father", labelI18n: { es: "El padre", en: "The father" } },
            { value: "relative", labelI18n: { es: "Otro familiar", en: "Another relative" } },
          ],
          isRequired: true,
          position: 0,
          source: "client_answer",
          validation: null,
          prefillValue: null,
          isPrefilled: false,
          currentAnswer: null,
        },
        {
          id: "q5",
          groupId: "g2",
          questionI18n: {
            es: "¿Cuántos años lleva el menor en EE. UU.?",
            en: "How many years has the minor been in the US?",
          },
          helpI18n: null,
          fieldType: "number",
          options: null,
          isRequired: false,
          position: 1,
          source: "client_answer",
          validation: { min: 0, max: 30 },
          prefillValue: null,
          isPrefilled: false,
          currentAnswer: null,
        },
      ],
    },
    {
      id: "g3",
      titleI18n: { es: "Tu relato", en: "Your account" },
      position: 2,
      questions: [
        {
          id: "q6",
          groupId: "g3",
          questionI18n: {
            es: "Cuéntanos sobre el día a día del menor",
            en: "Tell us about the minor's daily life",
          },
          helpI18n: {
            es: "Escuela, salud, su rutina. Lo que sientas importante.",
            en: "School, health, routine. Whatever feels important.",
          },
          fieldType: "textarea",
          options: null,
          isRequired: false,
          position: 0,
          source: "client_answer",
          validation: null,
          prefillValue: null,
          isPrefilled: false,
          currentAnswer: null,
        },
      ],
    },
  ],
};

/** Mi Historia (ai_letter) — narrative steps with per-textarea dictation. */
export const historiaFormMock: WizardForm = {
  responseId: "resp-h",
  formDefinitionId: "form-historia",
  labelI18n: { es: "Mi Historia", en: "My Story" },
  kind: "ai_letter",
  sourceLanguage: "en",
  isPerParty: false,
  versionId: "vh",
  status: "draft",
  submittedAt: null,
  filledPdfPath: null,
  filledBy: "client",
  groups: [
    {
      id: "h1",
      titleI18n: { es: "", en: "" },
      position: 0,
      questions: [
        {
          id: "hq1",
          groupId: "h1",
          questionI18n: { es: "¿Quién cuida del menor actualmente?", en: "Who cares for the minor right now?" },
          helpI18n: {
            es: "Cuéntanos sobre la persona que tiene la custodia hoy.",
            en: "Tell us about who has custody today.",
          },
          fieldType: "textarea",
          options: null,
          isRequired: true,
          position: 0,
          source: "client_answer",
          validation: null,
          prefillValue: null,
          isPrefilled: false,
          currentAnswer: "Mi hermana y yo cuidamos a Mateo desde 2023…",
        },
      ],
    },
    {
      id: "h2",
      titleI18n: { es: "", en: "" },
      position: 1,
      questions: [
        {
          id: "hq2",
          groupId: "h2",
          questionI18n: { es: "¿Cómo es la vida del menor aquí?", en: "What is the minor's life like here?" },
          helpI18n: {
            es: "Escuela, salud, su día a día. Lo que sientas importante.",
            en: "School, health, daily life.",
          },
          fieldType: "textarea",
          options: null,
          isRequired: false,
          position: 0,
          source: "client_answer",
          validation: null,
          prefillValue: null,
          isPrefilled: false,
          currentAnswer: null,
        },
      ],
    },
  ],
};

export const wizardSubmittedMock: WizardForm = {
  ...wizardFormMock,
  status: "submitted",
  submittedAt: "2026-06-10T12:00:00Z",
};
