/**
 * Form editor microcopy (DOC-53 §5 + PROMPT-ADM-05). Resolved from next-intl
 * (staff.admin.formEditor.*) by the RSC page and passed as a flat record so the
 * client feature stays i18n-agnostic (same pattern as catalog-wizard strings).
 */

export type FormEditorStrings = Record<string, string>;

/** Fallback ES strings — used by the dev preview where there's no i18n context. */
export const FORM_EDITOR_STRINGS_ES: FormEditorStrings = {
  // breadcrumb / header
  immutableBanner: "Esta versión es inmutable. Para cambiarla, crea una versión nueva.",
  versionDraft: "borrador",
  versionPublished: "publicada",
  versionArchived: "archivada",
  newVersion: "Nueva versión",
  newVersionNote: "Cada revisión del PDF oficial es una versión nueva — nunca se pisa la anterior.",
  editableCopy: "Crear versión editable",
  editableCopyNote: "Copia esta versión a un borrador editable (las preguntas se copian; la publicada queda intacta).",
  // stages
  stageUpload: "Subir PDF",
  stageStructure: "Estructurar",
  stagePreview: "Previsualizar",
  stagePublish: "Publicar",
  // upload
  dropzoneTitle: "Sube el PDF oficial (USCIS, EOIR o estatal).",
  dropzoneSub: "Detectaremos sus campos automáticamente.",
  dropzoneCta: "Elegir PDF",
  sourceLanguage: "Idioma del formulario oficial",
  sourceLanguageHint: "Si el cliente eligió español y el formulario está en inglés, sus respuestas se traducen al llenar el PDF.",
  reading: "Leyendo el formulario…",
  redetect: "Re-detectar",
  fieldsDetected: "campos detectados",
  byType: "Por tipo",
  byPage: "Por página",
  noFieldsTitle: "Este PDF no tiene campos rellenables (¿es un escaneo?).",
  noFieldsSub: "Prueba con el PDF oficial interactivo o normalízalo.",
  // structure
  aiPropose: "✦ Generar propuesta con IA",
  aiModeReplace: "Reemplazar lo no confirmado",
  aiModeMerge: "Fusionar con lo existente",
  aiPagesLabel: "Solo estas páginas del PDF (se fusiona)",
  aiPagesFrom: "Desde",
  aiPagesTo: "Hasta",
  aiPagesGo: "Generar páginas",
  aiPagesInvalid: "Rango de páginas inválido.",
  addGroup: "+ Grupo",
  addQuestion: "+ Pregunta en este grupo",
  aiOverlay: "Lex está leyendo el formulario y proponiendo preguntas en español e inglés…",
  structureEmpty: "Aún no hay preguntas. Genera una propuesta con IA o agrega un grupo manualmente.",
  aiFailed: "No se pudo generar la propuesta. Puedes estructurarlo manualmente.",
  proposed: "Propuesta",
  renameGroup: "Renombrar",
  reproposeGroup: "Re-proponer este grupo",
  deleteGroup: "Eliminar grupo",
  deleteGroupConfirm: "Este grupo tiene preguntas. ¿Eliminarlo de todas formas?",
  doNotFillOn: "No llenar esta sección",
  doNotFillOff: "Volver a llenar esta sección",
  doNotFillBadge: "No se llena",
  doNotFillHint:
    "Se deja en blanco en el PDF por diseño (p. ej. la firma del solicitante, o las Partes F/G del I-589 que se completan en la entrevista/audiencia).",
  questionWording: "Redacción",
  questionHelp: "Ayuda",
  fieldType: "Tipo",
  ftText: "Texto",
  ftNumber: "Número",
  ftDate: "Fecha",
  ftCheckbox: "Checkbox",
  ftSelect: "Desplegable",
  ftTextarea: "Párrafo",
  ftMultiselect: "Multi-selección",
  options: "Opciones",
  addOption: "+ Opción",
  optionsRequired: "Un desplegable necesita al menos una opción.",
  required: "Obligatoria",
  validation: "Validación avanzada",
  minSelected: "Mínimo a marcar (multi-selección)",
  // condition (dynamic/conditional fields)
  condition: "Mostrar según otra respuesta",
  condNone: "Siempre visible",
  condShow: "Mostrar solo si…",
  condLock: "Bloquear con mensaje si no…",
  condRequire: "Obligatoria solo si…",
  condWhenQuestion: "Pregunta que la controla",
  condOp: "Condición",
  condValue: "Valor",
  condLockMessage: "Mensaje cuando está bloqueada",
  condOpEquals: "es igual a",
  condOpNotEquals: "no es igual a",
  condOpIncludes: "incluye",
  condOpAnswered: "está respondida",
  condOpGte: "≥ mayor o igual a",
  condOpLte: "≤ menor o igual a",
  condPickQuestion: "Elige una pregunta…",
  condHint:
    "La pregunta solo aplica cuando se cumple la condición (p. ej. Sí/No → explicación, o campos de continuación como el 5.º hijo).",
  pdfMapping: "Campo del PDF",
  pdfMappingHint: "o haz clic en el campo dentro del PDF (derecha) para mapearlo aquí",
  fieldAssigned: "Campo asignado a la pregunta",
  noPdfField: "Sin campo (dato auxiliar)",
  dupFieldWarn: "Otra pregunta ya está mapeada a este campo.",
  origin: "Origen",
  originClient: "El cliente",
  originAiField: "IA (campo)",
  originDoc: "Extracción de doc.",
  originGen: "Otra generación",
  originProfile: "Perfil",
  originClientNote: "El cliente la responde en su wizard.",
  originNotShown: "Esta pregunta NO se muestra al cliente: se pre-llena al ejecutar y el equipo puede corregirla.",
  aiFieldConnect: "Conectar con",
  aiFieldKindDocument: "Documento",
  aiFieldKindLetter: "Carta / generación",
  aiFieldPickDocument: "Documento (la IA lo interpreta)",
  aiFieldPickLetter: "Carta de origen (la IA sintetiza)",
  aiFieldPickConnected: "Origen conectado",
  aiFieldModel: "Modelo (opcional)",
  aiFieldModelAuto: "Automático",
  aiFieldInstruction: "Instrucción para la IA (qué escribir en este campo)",
  aiFieldInstructionHint: "Ej. Redacta la narrativa de persecución de la Parte B a partir del memorándum.",
  companionTitle: "Cuestionario complementario",
  companionHint: "Preguntas para nutrir la redacción de alta calidad. Sus respuestas alimentan esta generación.",
  companionOpen: "Abrir cuestionario",
  companionCreate: "Generar cuestionario",
  pickDocument: "Documento de origen",
  pickPath: "Ruta del dato",
  pickForm: "Formulario de origen",
  pickProfileField: "Campo del perfil",
  piiLocked: "Se resuelve localmente, nunca pasa por la IA.",
  moveToGroup: "Mover a grupo…",
  deleteQuestion: "Eliminar pregunta",
  autosaved: "Guardado hace un momento",
  saving: "Guardando…",
  // viewer
  viewOfficialPdf: "Ver PDF oficial",
  legendMapped: "mapeado",
  legendUnmapped: "sin mapear",
  legendSelected: "seleccionado",
  mappedCounter: "{n} de {total} campos mapeados",
  pageLabel: "Pág.",
  // preview
  previewToggleEs: "ES",
  previewToggleEn: "EN",
  generateTestPdf: "Generar PDF de prueba",
  prefillFrom: "Se pre-llenará desde {origin}",
  testGaps: "Campos requeridos sin respuesta (no bloquean):",
  editThisQuestion: "Editar esta pregunta",
  // publish
  publishTitle: "Lista de publicación",
  publishBtn: "Publicar versión {n}",
  publishBlocking: "Bloqueantes",
  publishWarnings: "Avisos",
  ackUnmapped: "Confirmo que estos campos quedan sin llenar (p. ej. 'For office use only').",
  publishedBanner: "Versión {n} publicada. Los casos que ya empezaron siguen con su versión; los nuevos usan esta.",
  unpublish: "Despublicar",
  unpublishConfirm: "El formulario quedará sin versión activa y no se ofrecerá en casos nuevos.",
  allClear: "Todo en orden. Puedes publicar.",
  // ai_letter
  systemPrompt: "System prompt",
  promptTokens: "~{n} tokens",
  variables: "Variables disponibles",
  inputDocs: "Documentos de entrada",
  inputForms: "Formularios de entrada",
  dataset: "Dataset",
  datasetExceeds: "El motor inyectará un subconjunto.",
  manageDatasets: "Gestionar datasets",
  model: "Modelo",
  maxTokens: "Tokens de salida",
  outputFormat: "Formato",
  outputLanguage: "Idioma",
  langEs: "Español",
  langEn: "Inglés",
  langBoth: "Ambos",
  configFrozenNote: "Cambiar esta configuración no afecta corridas pasadas: cada corrida congela su configuración.",
  saveConfig: "Guardar configuración",
  configSaved: "Configuración guardada.",
  testWithCase: "Probar con un caso",
  searchCase: "Buscar por número o cliente…",
  precheck: "Pre-chequeo de insumos",
  testGenerate: "Probar generación",
  testRunning: "Generando…",
  testResult: "Resultado de la prueba",
  tokensInOut: "Tokens entrada / salida",
  cost: "Coste",
  frozenConfig: "Configuración congelada",
  testsDontCount: "Las pruebas no cuentan en las métricas de negocio.",
  none: "Ninguno",
  retry: "Reintentar",
};
