/**
 * Email block model — the visual campaign composer's source of truth.
 *
 * Lives in shared/ so BOTH the frontend editor (live preview, composer) and the
 * backend campaigns service (derive body_html, interpolate per recipient) use the
 * exact same types and renderer — they can never drift.
 *
 * SECURITY: `renderBlocksToHtml` is a TRUSTED renderer. The structure and inline
 * styles are generated by this code; the only user-controlled inputs (text, urls,
 * alt) are HTML-escaped / scheme-validated here. Because of that, block-derived
 * body_html does NOT go through the free-form `sanitizeCampaignHtml` (whose strict
 * style allowlist would strip the layout) — this renderer IS the boundary.
 */

import { escapeHtml } from "./html";

// ---------------------------------------------------------------------------
// Block model
// ---------------------------------------------------------------------------

export type EmailBlock =
  | { id: string; type: "heading"; text: string }
  | { id: string; type: "text"; text: string }
  | { id: string; type: "button"; label: string; url: string }
  | { id: string; type: "image"; url: string; alt: string }
  | { id: string; type: "divider" }
  | { id: string; type: "spacer" };

export type EmailBlockType = EmailBlock["type"];

export const EMAIL_BLOCK_TYPES: EmailBlockType[] = [
  "heading",
  "text",
  "button",
  "image",
  "divider",
  "spacer",
];

/** Factory for the composer — the caller supplies the id (kept pure for tests). */
export function emptyBlock(type: EmailBlockType, id: string): EmailBlock {
  switch (type) {
    case "heading":
      return { id, type, text: "Título" };
    case "text":
      return { id, type, text: "Escribe tu mensaje aquí…" };
    case "button":
      return { id, type, label: "Ver más", url: "https://x-legal.usalatinoprime.com" };
    case "image":
      return { id, type, url: "", alt: "" };
    case "divider":
      return { id, type };
    case "spacer":
      return { id, type };
  }
}

// ---------------------------------------------------------------------------
// Merge fields (personalisation) — resolved per recipient at send time
// ---------------------------------------------------------------------------

export const MERGE_FIELDS = [
  { token: "{{nombre}}", labelEs: "Nombre del cliente", labelEn: "Client first name" },
  { token: "{{org}}", labelEs: "Nombre de la empresa", labelEn: "Company name" },
] as const;

export interface MergeVars {
  nombre?: string;
  org?: string;
}

/**
 * Replaces merge tokens with per-recipient values. Unknown / missing values
 * collapse to an empty string (safe default).
 *
 * - `escape: true` (default) — for HTML bodies: values are HTML-escaped so a
 *   recipient's name can never inject markup.
 * - `escape: false` — for plain-text subjects: values are used raw but CR/LF is
 *   stripped (defends against email header injection).
 */
export function interpolateMergeFields(
  input: string,
  vars: MergeVars,
  opts?: { escape?: boolean },
): string {
  const escape = opts?.escape ?? true;
  const v = (s: string | undefined): string => {
    const raw = s ?? "";
    return escape ? escapeHtml(raw) : raw.replace(/[\r\n]+/g, " ").trim();
  };
  return input
    .replace(/\{\{\s*nombre\s*\}\}/gi, v(vars.nombre))
    .replace(/\{\{\s*org\s*\}\}/gi, v(vars.org));
}

// ---------------------------------------------------------------------------
// Trusted HTML renderer (email-client safe; inline styles, table buttons)
// ---------------------------------------------------------------------------

/** Allows only http(s) URLs; everything else (javascript:, data:, …) → "#". */
function safeUrl(url: string): string {
  const trimmed = (url ?? "").trim();
  if (/^https?:\/\//i.test(trimmed)) return escapeHtml(trimmed);
  return "#";
}

function renderBlock(b: EmailBlock): string {
  switch (b.type) {
    case "heading":
      return `<h2 style="margin:0 0 12px;font-size:22px;font-weight:800;color:#0f172a;line-height:1.3">${escapeHtml(b.text)}</h2>`;
    case "text":
      return `<p style="margin:0 0 16px;font-size:15px;line-height:1.7;color:#334155">${escapeHtml(b.text).replace(/\n/g, "<br/>")}</p>`;
    case "button":
      return (
        `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:8px 0 22px">` +
        `<tr><td style="border-radius:10px;background:#2F6BFF">` +
        `<a href="${safeUrl(b.url)}" style="display:inline-block;padding:13px 30px;font-size:15px;font-weight:700;color:#ffffff;text-decoration:none;border-radius:10px">${escapeHtml(b.label)}</a>` +
        `</td></tr></table>`
      );
    case "image":
      if (!b.url.trim()) return "";
      return `<img src="${safeUrl(b.url)}" alt="${escapeHtml(b.alt)}" style="max-width:100%;height:auto;border-radius:12px;margin:0 0 16px;display:block"/>`;
    case "divider":
      return `<hr style="border:none;border-top:1px solid #e5e7eb;margin:22px 0"/>`;
    case "spacer":
      return `<div style="height:24px;line-height:24px">&nbsp;</div>`;
  }
}

/** Renders a block list to the inner HTML that CampaignEmail wraps (header/footer). */
export function renderBlocksToHtml(blocks: EmailBlock[]): string {
  return blocks.map(renderBlock).join("\n");
}

// ---------------------------------------------------------------------------
// Starter templates (the composer opens from one of these)
// ---------------------------------------------------------------------------

/** Distributes Omit over the union so each variant keeps its own fields. */
type DistributiveOmit<T, K extends PropertyKey> = T extends unknown ? Omit<T, K> : never;

/** A block without its id — the shape stored in starter templates. */
export type EmailBlockDraft = DistributiveOmit<EmailBlock, "id">;

export interface BlockTemplate {
  key: string;
  nameEs: string;
  nameEn: string;
  subject: string;
  blocks: EmailBlockDraft[];
}

export const BLOCK_TEMPLATES: BlockTemplate[] = [
  {
    key: "novedad",
    nameEs: "Novedad",
    nameEn: "News update",
    subject: "Novedades de UsaLatinoPrime",
    blocks: [
      { type: "heading", text: "Hola {{nombre}}, tenemos novedades" },
      { type: "text", text: "Queremos contarte lo último que está pasando en {{org}} y cómo puede ayudarte en tu proceso." },
      { type: "button", label: "Ver más", url: "https://x-legal.usalatinoprime.com" },
    ],
  },
  {
    key: "promo",
    nameEs: "Promoción",
    nameEn: "Promotion",
    subject: "Una oferta pensada para ti",
    blocks: [
      { type: "heading", text: "{{nombre}}, esto es para ti 🎁" },
      { type: "text", text: "Por tiempo limitado tenemos un beneficio especial para que continúes tu camino con nosotros." },
      { type: "button", label: "Aprovechar ahora", url: "https://x-legal.usalatinoprime.com" },
      { type: "text", text: "Aplican términos y condiciones." },
    ],
  },
  {
    key: "recordatorio",
    nameEs: "Recordatorio de cita",
    nameEn: "Appointment reminder",
    subject: "Recordatorio de tu próxima cita",
    blocks: [
      { type: "heading", text: "{{nombre}}, no olvides tu cita" },
      { type: "text", text: "Tienes una cita próxima con tu equipo. Prepara tus documentos y conéctate a tiempo." },
      { type: "button", label: "Ver mi cita", url: "https://x-legal.usalatinoprime.com" },
    ],
  },
  {
    key: "comunidad",
    nameEs: "Comunidad",
    nameEn: "Community",
    subject: "Te invitamos a nuestra comunidad",
    blocks: [
      { type: "heading", text: "Bienvenido a la comunidad de {{org}}" },
      { type: "text", text: "Únete a las charlas en vivo, resuelve tus dudas y conecta con personas que viven tu mismo proceso." },
      { type: "button", label: "Entrar a la comunidad", url: "https://x-legal.usalatinoprime.com" },
    ],
  },
];
