/**
 * Integrations module — pure domain (Zod schemas, serializers, pure functions).
 *
 * NO I/O. All functions are deterministic, testable with zero mocks.
 * Mirrors the SaaS Abogados contract (DOC-70) exactly.
 *
 * @module integrations/domain
 */

import { z } from "zod";
import { canonicalClientLabel } from "@/backend/modules/expediente";
import {
  DOCUMENT_KINDS,
  FINDING_SEVERITIES,
  SEMAFORO_COLORS,
  RETURN_TO,
} from "@/shared/constants/integrations";

// ---------------------------------------------------------------------------
// Status constants
// ---------------------------------------------------------------------------

/** Statuses in V2 `legal_validations` that block a new send attempt. */
export const LEGAL_VALIDATION_ACTIVE_STATUSES = [
  "pending",
  "sent",
  "queued",
  "in_review",
] as const;

export type LegalValidationActiveStatus =
  (typeof LEGAL_VALIDATION_ACTIVE_STATUSES)[number];

export const LEGAL_VALIDATION_STATUSES = [
  "pending",
  "sent",
  "queued",
  "in_review",
  "validated",
  "needs_corrections",
  "error",
  "cancelled",
] as const;

export type LegalValidationStatus =
  (typeof LEGAL_VALIDATION_STATUSES)[number];

// ---------------------------------------------------------------------------
// Zod schemas — mirrors of the SaaS contract (DOC-70 §2.1, §3, §4.1, §6)
// ---------------------------------------------------------------------------

// Lenient UUID — accepts both proper UUID and arbitrary external IDs
const zUuid = z.string().min(1);

/** Single document in the POST payload (DOC-70 §2.4). */
export const AbogadosDocumentSchema = z.object({
  name: z.string().min(1),
  kind: z.enum(DOCUMENT_KINDS).default("declaration"),
  content: z.string().min(1),
});

export type AbogadosDocument = z.infer<typeof AbogadosDocumentSchema>;

/** Review block (V2.0 always sends null — DOC-70 §2.5). */
export const AbogadosReviewSchema = z
  .object({
    score: z.number().int().min(0).max(100),
    ready_to_file: z.boolean(),
    summary: z.string(),
    findings: z.array(z.unknown()),
    strengths: z.array(z.string()),
    playbook_name: z.string().nullish(),
    reviewer_model: z.string().nullish(),
  })
  .nullish();

/** POST /api/integration/validations payload (DOC-70 §2.1). */
export const AbogadosPostPayloadSchema = z.object({
  external_case_id: zUuid,
  source: z.string().min(1),
  case_number: z.string().nullish(),
  service_slug: z.string().nullish(),
  service_name: z.string().nullish(),
  client_label: z.string().nullish(),
  documents: z.array(AbogadosDocumentSchema).min(1),
  review: AbogadosReviewSchema,
  callback_url: z.string().url().nullish(),
});

export type AbogadosPostPayload = z.infer<typeof AbogadosPostPayloadSchema>;

/** POST response from SaaS (202 or 200-dedup — DOC-70 §3). */
export const AbogadosPostResponseSchema = z.object({
  validation_id: z.string(),
  status: z.string(),
  semaforo: z.enum(SEMAFORO_COLORS).nullable().optional(),
  prereview: z.string().optional(),
  deduplicated: z.boolean().optional(),
});

export type AbogadosPostResponse = z.infer<typeof AbogadosPostResponseSchema>;

/** Single verdict finding (DOC-70 §4.1). */
export const AbogadosFindingSchema = z.object({
  severity: z.enum(FINDING_SEVERITIES),
  category: z.string(),
  location: z.string(),
  description: z.string(),
  recommendation: z.string(),
});

export type AbogadosFinding = z.infer<typeof AbogadosFindingSchema>;

/** Inbound webhook payload (DOC-70 §4.1 — generated by SaaS webhook.ts). */
export const AbogadosVerdictWebhookSchema = z.object({
  event: z.literal("validation.verdict"),
  validation_id: z.string().min(1),
  external_case_id: z.string().min(1),
  source: z.string().min(1),
  case_number: z.string().nullish(),
  verdict: z.enum(["validated", "needs_corrections", "cancelled"]),
  verdict_notes: z.string().nullish(),
  verdict_findings: z.array(AbogadosFindingSchema).nullish(),
  verdict_at: z.string().min(1),
  review_seconds: z.number().nullish(),
  return_to: z.enum(RETURN_TO).nullish(),
  semaforo: z.enum(SEMAFORO_COLORS).nullish(),
  ai_score: z.number().int().min(0).max(100).nullish(),
});

export type AbogadosVerdictWebhook = z.infer<typeof AbogadosVerdictWebhookSchema>;

/** GET /api/integration/validations/{externalCaseId} response (DOC-70 §6). */
export const AbogadosPollingResponseSchema = z.object({
  validation: z.object({
    id: z.string(),
    external_case_id: z.string(),
    source: z.string(),
    case_number: z.string().nullish(),
    status: z.string(),
    semaforo: z.enum(SEMAFORO_COLORS).nullish(),
    ai_score: z.number().nullish(),
    prereview_status: z.string().nullish(),
    enqueued_at: z.string().nullish(),
    verdict: z.enum(["validated", "needs_corrections", "cancelled"]).nullish(),
    verdict_notes: z.string().nullish(),
    verdict_findings: z.array(AbogadosFindingSchema).nullish(),
    verdict_at: z.string().nullish(),
    review_seconds: z.number().nullish(),
    return_to: z.enum(RETURN_TO).nullish(),
    webhook_delivered_at: z.string().nullish(),
  }),
});

export type AbogadosPollingResponse = z.infer<typeof AbogadosPollingResponseSchema>;

// ---------------------------------------------------------------------------
// buildClientLabel — DOC-70 §2.3
// ---------------------------------------------------------------------------

/**
 * Derives the canonical "{F}. {LastName}" label from a client's name.
 *
 * Delegates to `canonicalClientLabel` from the expediente module (same rule).
 * DOC-70 §2.3: initial of first name + first word of last name (with particle).
 * The expediente module's implementation takes the full last name as-is.
 *
 * Example: "Juan", "Vásquez" → "J. Vásquez"
 * Example: "María José", "De La Cruz" → "M. De La Cruz"
 */
export function buildClientLabel(firstName: string, lastName: string): string {
  return canonicalClientLabel(firstName, lastName);
}

// ---------------------------------------------------------------------------
// SerializeAutomatedForm input type
// ---------------------------------------------------------------------------

export interface SerializeFormQuestion {
  id: string;
  question_i18n: { es: string; en?: string };
  pdf_field_name: string;
  field_type: string;
  is_required: boolean;
  options: Array<{ value: string; label_i18n: { es: string; en?: string } }> | null;
  answer: unknown;
}

export interface SerializeFormGroup {
  id: string;
  title_i18n: { es: string; en?: string };
  position: number;
  questions: SerializeFormQuestion[];
}

export interface SerializeFormInput {
  /** Human-readable form label (e.g. "I-360 — Petition for Amerasian"). */
  label: string;
  /** Numeric version of the published automation. */
  versionNo: number;
  /** Label for the version (e.g. "publicada"). */
  versionLabel: string;
  /** Optional party label (e.g. "Mateo V. (minor)"). */
  partyLabel: string | null;
  groups: SerializeFormGroup[];
}

// ---------------------------------------------------------------------------
// serializeAutomatedForm — DOC-70 §2.4.1
// ---------------------------------------------------------------------------

/**
 * Serializes an automated form (AcroForm responses) into deterministic
 * plain text for the SaaS Abogados validation package.
 *
 * Format (DOC-70 §2.4.1):
 *   FORMULARIO: {label}
 *   Versión de automatización: {n} ({versionLabel})  ·  Parte: {partyLabel?}
 *
 *   ### {group.title_i18n.es}
 *   {question_i18n.es} [{pdf_field_name}]: {value}
 *   ...
 *
 * Value formatting rules:
 *   - date: YYYY-MM-DD (passthrough — stored as ISO date string)
 *   - checkbox: "Sí" / "No"
 *   - select: "{label_i18n.es} ({value})"
 *   - required + null answer: "[SIN RESPUESTA]"
 *   - optional + null answer: skipped (empty line not emitted)
 */
export function serializeAutomatedForm(form: SerializeFormInput): string {
  const lines: string[] = [];

  // Header
  lines.push(`FORMULARIO: ${form.label}`);
  const versionLine = `Versión de automatización: ${form.versionNo} (${form.versionLabel})`;
  if (form.partyLabel) {
    lines.push(`${versionLine}  ·  Parte: ${form.partyLabel}`);
  } else {
    lines.push(versionLine);
  }

  // Groups (sorted by position ascending)
  const sortedGroups = [...form.groups].sort((a, b) => a.position - b.position);

  for (const group of sortedGroups) {
    lines.push("");
    lines.push(`### ${group.title_i18n.es}`);

    for (const q of group.questions) {
      const formattedValue = formatQuestionValue(q);
      if (formattedValue === null) {
        // Optional with no answer — skip
        continue;
      }
      lines.push(`${q.question_i18n.es} [${q.pdf_field_name}]: ${formattedValue}`);
    }
  }

  return lines.join("\n");
}

function formatQuestionValue(q: SerializeFormQuestion): string | null {
  const { answer, field_type, is_required, options } = q;

  if (answer === null || answer === undefined || answer === "") {
    if (is_required) return "[SIN RESPUESTA]";
    return null; // optional + no answer → skip
  }

  if (field_type === "checkbox") {
    return answer ? "Sí" : "No";
  }

  if (field_type === "select" && options) {
    const found = options.find((o) => o.value === answer);
    if (found) {
      return `${found.label_i18n.es} (${found.value})`;
    }
    return String(answer);
  }

  // text, date, number, textarea — passthrough
  return String(answer);
}

// ---------------------------------------------------------------------------
// buildAnnexIndex — DOC-70 §2.4
// ---------------------------------------------------------------------------

export interface AnnexIndexItem {
  position: number;
  title: string;
  item_type: string;
  page_count: number | null;
  /** True if text travels in the package (ai_generation, automated_form, client_document with extraction). */
  textIncluded: boolean;
}

/**
 * Builds the "Índice del expediente y anexos no incluidos" document.
 *
 * Always the LAST document in the SaaS package. Lists ALL expediente items
 * in position order so the lawyer knows what physical evidence exists.
 *
 * Returns an AbogadosDocument ready to append to the documents[] array.
 */
export function buildAnnexIndex(
  items: AnnexIndexItem[],
): { name: string; kind: "other"; content: string } {
  const sorted = [...items].sort((a, b) => a.position - b.position);

  const lines: string[] = ["Índice del expediente", ""];

  for (const item of sorted) {
    const pageInfo = item.page_count != null ? ` | ${item.page_count} pág.` : "";
    const textInfo = item.textIncluded
      ? "[texto incluido en paquete]"
      : "[solo referencia — no incluido]";
    lines.push(
      `${item.position}. ${item.title} (${item.item_type}${pageInfo}) — ${textInfo}`,
    );
  }

  return {
    name: "Índice del expediente y anexos no incluidos",
    kind: "other",
    content: lines.join("\n"),
  };
}
